# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:42:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class ARN(RootModel[constr(min_length=20, max_length=2048)]):
    root: constr(min_length=20, max_length=2048)


class AccessDeniedException(RootModel[Any]):
    root: Any


class AccountID(RootModel[constr(pattern=r'[0-9]{12,}', min_length=12, max_length=12)]):
    root: constr(pattern=r'[0-9]{12,}', min_length=12, max_length=12)


class ActionCategory(Enum):
    DISASTER_RECOVERY = 'DISASTER_RECOVERY'
    OPERATING_SYSTEM = 'OPERATING_SYSTEM'
    LICENSE_AND_SUBSCRIPTION = 'LICENSE_AND_SUBSCRIPTION'
    VALIDATION = 'VALIDATION'
    OBSERVABILITY = 'OBSERVABILITY'
    SECURITY = 'SECURITY'
    NETWORKING = 'NETWORKING'
    CONFIGURATION = 'CONFIGURATION'
    BACKUP = 'BACKUP'
    OTHER = 'OTHER'


class ActionDescription(
    RootModel[
        constr(pattern=r'^[0-9a-zA-Z ():/.,\'-_#*; ]*$', min_length=0, max_length=256)
    ]
):
    root: constr(pattern=r'^[0-9a-zA-Z ():/.,\'-_#*; ]*$', min_length=0, max_length=256)


class ActionID(RootModel[constr(pattern=r'[0-9a-zA-Z]$', min_length=1, max_length=64)]):
    root: constr(pattern=r'[0-9a-zA-Z]$', min_length=1, max_length=64)


class ActionIDs(RootModel[List[ActionID]]):
    root: List[ActionID] = Field(..., max_length=100, min_length=0)


class ActionName(
    RootModel[
        constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)
    ]
):
    root: constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)


class ApplicationDescription(
    RootModel[constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)]
):
    root: constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)


class ApplicationHealthStatus(Enum):
    HEALTHY = 'HEALTHY'
    LAGGING = 'LAGGING'
    ERROR = 'ERROR'


class ApplicationID(
    RootModel[constr(pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)]
):
    root: constr(pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)


class ApplicationIDs(RootModel[List[ApplicationID]]):
    root: List[ApplicationID] = Field(..., max_length=50, min_length=1)


class ApplicationIDsFilter(RootModel[List[ApplicationID]]):
    root: List[ApplicationID] = Field(..., max_length=200, min_length=0)


class ApplicationName(
    RootModel[
        constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)
    ]
):
    root: constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)


class ApplicationProgressStatus(Enum):
    NOT_STARTED = 'NOT_STARTED'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'


class ArchiveApplicationRequest(BaseModel):
    applicationID: ApplicationID


class AssociateApplicationsResponse(BaseModel):
    pass


class AssociateSourceServersResponse(BaseModel):
    pass


class Boolean(RootModel[bool]):
    root: bool


class BootMode(Enum):
    LEGACY_BIOS = 'LEGACY_BIOS'
    UEFI = 'UEFI'


class BoundedString(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class ChangeServerLifeCycleStateSourceServerLifecycleState(Enum):
    READY_FOR_TEST = 'READY_FOR_TEST'
    READY_FOR_CUTOVER = 'READY_FOR_CUTOVER'
    CUTOVER = 'CUTOVER'


class ClientIdempotencyToken(RootModel[constr(min_length=0, max_length=64)]):
    root: constr(min_length=0, max_length=64)


class CloudWatchLogGroupName(
    RootModel[constr(pattern=r'^[\.\-_/#A-Za-z0-9]+$', min_length=1, max_length=512)]
):
    root: constr(pattern=r'^[\.\-_/#A-Za-z0-9]+$', min_length=1, max_length=512)


class ConflictException(RootModel[Any]):
    root: Any


class DataReplicationErrorString(Enum):
    AGENT_NOT_SEEN = 'AGENT_NOT_SEEN'
    SNAPSHOTS_FAILURE = 'SNAPSHOTS_FAILURE'
    NOT_CONVERGING = 'NOT_CONVERGING'
    UNSTABLE_NETWORK = 'UNSTABLE_NETWORK'
    FAILED_TO_CREATE_SECURITY_GROUP = 'FAILED_TO_CREATE_SECURITY_GROUP'
    FAILED_TO_LAUNCH_REPLICATION_SERVER = 'FAILED_TO_LAUNCH_REPLICATION_SERVER'
    FAILED_TO_BOOT_REPLICATION_SERVER = 'FAILED_TO_BOOT_REPLICATION_SERVER'
    FAILED_TO_AUTHENTICATE_WITH_SERVICE = 'FAILED_TO_AUTHENTICATE_WITH_SERVICE'
    FAILED_TO_DOWNLOAD_REPLICATION_SOFTWARE = 'FAILED_TO_DOWNLOAD_REPLICATION_SOFTWARE'
    FAILED_TO_CREATE_STAGING_DISKS = 'FAILED_TO_CREATE_STAGING_DISKS'
    FAILED_TO_ATTACH_STAGING_DISKS = 'FAILED_TO_ATTACH_STAGING_DISKS'
    FAILED_TO_PAIR_REPLICATION_SERVER_WITH_AGENT = (
        'FAILED_TO_PAIR_REPLICATION_SERVER_WITH_AGENT'
    )
    FAILED_TO_CONNECT_AGENT_TO_REPLICATION_SERVER = (
        'FAILED_TO_CONNECT_AGENT_TO_REPLICATION_SERVER'
    )
    FAILED_TO_START_DATA_TRANSFER = 'FAILED_TO_START_DATA_TRANSFER'
    UNSUPPORTED_VM_CONFIGURATION = 'UNSUPPORTED_VM_CONFIGURATION'
    LAST_SNAPSHOT_JOB_FAILED = 'LAST_SNAPSHOT_JOB_FAILED'


class DataReplicationInitiationStepName(Enum):
    WAIT = 'WAIT'
    CREATE_SECURITY_GROUP = 'CREATE_SECURITY_GROUP'
    LAUNCH_REPLICATION_SERVER = 'LAUNCH_REPLICATION_SERVER'
    BOOT_REPLICATION_SERVER = 'BOOT_REPLICATION_SERVER'
    AUTHENTICATE_WITH_SERVICE = 'AUTHENTICATE_WITH_SERVICE'
    DOWNLOAD_REPLICATION_SOFTWARE = 'DOWNLOAD_REPLICATION_SOFTWARE'
    CREATE_STAGING_DISKS = 'CREATE_STAGING_DISKS'
    ATTACH_STAGING_DISKS = 'ATTACH_STAGING_DISKS'
    PAIR_REPLICATION_SERVER_WITH_AGENT = 'PAIR_REPLICATION_SERVER_WITH_AGENT'
    CONNECT_AGENT_TO_REPLICATION_SERVER = 'CONNECT_AGENT_TO_REPLICATION_SERVER'
    START_DATA_TRANSFER = 'START_DATA_TRANSFER'


class DataReplicationInitiationStepStatus(Enum):
    NOT_STARTED = 'NOT_STARTED'
    IN_PROGRESS = 'IN_PROGRESS'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    SKIPPED = 'SKIPPED'


class DataReplicationState(Enum):
    STOPPED = 'STOPPED'
    INITIATING = 'INITIATING'
    INITIAL_SYNC = 'INITIAL_SYNC'
    BACKLOG = 'BACKLOG'
    CREATING_SNAPSHOT = 'CREATING_SNAPSHOT'
    CONTINUOUS = 'CONTINUOUS'
    PAUSED = 'PAUSED'
    RESCAN = 'RESCAN'
    STALLED = 'STALLED'
    DISCONNECTED = 'DISCONNECTED'
    PENDING_SNAPSHOT_SHIPPING = 'PENDING_SNAPSHOT_SHIPPING'
    SHIPPING_SNAPSHOT = 'SHIPPING_SNAPSHOT'


class DeleteApplicationRequest(BaseModel):
    applicationID: ApplicationID


class DeleteApplicationResponse(BaseModel):
    pass


class DeleteJobResponse(BaseModel):
    pass


class DeleteLaunchConfigurationTemplateResponse(BaseModel):
    pass


class DeleteReplicationConfigurationTemplateResponse(BaseModel):
    pass


class DeleteSourceServerResponse(BaseModel):
    pass


class DeleteWaveResponse(BaseModel):
    pass


class DescribeSourceServersRequestApplicationIDs(RootModel[List[ApplicationID]]):
    root: List[ApplicationID] = Field(..., max_length=200, min_length=0)


class DescribeVcenterClientsRequest(BaseModel):
    pass


class DisassociateApplicationsResponse(BaseModel):
    pass


class DisassociateSourceServersResponse(BaseModel):
    pass


class DocumentVersion(RootModel[constr(pattern=r'^(\$DEFAULT|\$LATEST|[0-9]+)$')]):
    root: constr(pattern=r'^(\$DEFAULT|\$LATEST|[0-9]+)$')


class EC2InstanceID(
    RootModel[constr(pattern=r'^i-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)]
):
    root: constr(pattern=r'^i-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)


class EC2InstanceType(RootModel[constr(min_length=0, max_length=255)]):
    root: constr(min_length=0, max_length=255)


class EC2LaunchConfigurationTemplateID(
    RootModel[constr(pattern=r'^lt-[0-9a-z]{17}$', min_length=20, max_length=20)]
):
    root: constr(pattern=r'^lt-[0-9a-z]{17}$', min_length=20, max_length=20)


class ExportID(
    RootModel[constr(pattern=r'^export-[0-9a-zA-Z]{17}$', min_length=24, max_length=24)]
):
    root: constr(pattern=r'^export-[0-9a-zA-Z]{17}$', min_length=24, max_length=24)


class ExportStatus(Enum):
    PENDING = 'PENDING'
    STARTED = 'STARTED'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'


class FirstBoot(Enum):
    WAITING = 'WAITING'
    SUCCEEDED = 'SUCCEEDED'
    UNKNOWN = 'UNKNOWN'
    STOPPED = 'STOPPED'


class Float(RootModel[float]):
    root: float


class IPsList(RootModel[List[BoundedString]]):
    root: List[BoundedString]


class ISO8601DatetimeString(
    RootModel[
        constr(
            pattern=r'^[1-9][0-9]*-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?Z$',
            min_length=19,
            max_length=32,
        )
    ]
):
    root: constr(
        pattern=r'^[1-9][0-9]*-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?Z$',
        min_length=19,
        max_length=32,
    )


class ISO8601DurationString(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class IdentificationHints(BaseModel):
    awsInstanceID: Optional[EC2InstanceID] = None
    fqdn: Optional[BoundedString] = None
    hostname: Optional[BoundedString] = None
    vmPath: Optional[BoundedString] = None
    vmWareUuid: Optional[BoundedString] = None


class ImportErrorType(Enum):
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    PROCESSING_ERROR = 'PROCESSING_ERROR'


class ImportID(
    RootModel[constr(pattern=r'^import-[0-9a-zA-Z]{17}$', min_length=24, max_length=24)]
):
    root: constr(pattern=r'^import-[0-9a-zA-Z]{17}$', min_length=24, max_length=24)


class ImportIDsFilter(RootModel[List[ImportID]]):
    root: List[ImportID] = Field(..., max_length=10, min_length=0)


class ImportStatus(Enum):
    PENDING = 'PENDING'
    STARTED = 'STARTED'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'


class InitializeServiceRequest(BaseModel):
    pass


class InitializeServiceResponse(BaseModel):
    pass


class InitiatedBy(Enum):
    START_TEST = 'START_TEST'
    START_CUTOVER = 'START_CUTOVER'
    DIAGNOSTIC = 'DIAGNOSTIC'
    TERMINATE = 'TERMINATE'


class InternalServerException(RootModel[Any]):
    root: Any


class JmesPathString(
    RootModel[
        constr(
            pattern=r'^[a-zA-Z0-9_]+(\.[a-zA-Z0-9_\[\]]+)*$',
            min_length=1,
            max_length=1011,
        )
    ]
):
    root: constr(
        pattern=r'^[a-zA-Z0-9_]+(\.[a-zA-Z0-9_\[\]]+)*$', min_length=1, max_length=1011
    )


class JobID(
    RootModel[constr(pattern=r'^mgnjob-[0-9a-zA-Z]{17}$', min_length=24, max_length=24)]
):
    root: constr(pattern=r'^mgnjob-[0-9a-zA-Z]{17}$', min_length=24, max_length=24)


class JobLogEvent(Enum):
    JOB_START = 'JOB_START'
    SERVER_SKIPPED = 'SERVER_SKIPPED'
    CLEANUP_START = 'CLEANUP_START'
    CLEANUP_END = 'CLEANUP_END'
    CLEANUP_FAIL = 'CLEANUP_FAIL'
    SNAPSHOT_START = 'SNAPSHOT_START'
    SNAPSHOT_END = 'SNAPSHOT_END'
    SNAPSHOT_FAIL = 'SNAPSHOT_FAIL'
    USING_PREVIOUS_SNAPSHOT = 'USING_PREVIOUS_SNAPSHOT'
    CONVERSION_START = 'CONVERSION_START'
    CONVERSION_END = 'CONVERSION_END'
    CONVERSION_FAIL = 'CONVERSION_FAIL'
    LAUNCH_START = 'LAUNCH_START'
    LAUNCH_FAILED = 'LAUNCH_FAILED'
    JOB_CANCEL = 'JOB_CANCEL'
    JOB_END = 'JOB_END'


class JobStatus(Enum):
    PENDING = 'PENDING'
    STARTED = 'STARTED'
    COMPLETED = 'COMPLETED'


class JobType(Enum):
    LAUNCH = 'LAUNCH'
    TERMINATE = 'TERMINATE'


class LargeBoundedString(RootModel[constr(min_length=0, max_length=65536)]):
    root: constr(min_length=0, max_length=65536)


class LaunchConfigurationTemplateID(
    RootModel[constr(pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)]
):
    root: constr(pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)


class LaunchConfigurationTemplateIDs(RootModel[List[LaunchConfigurationTemplateID]]):
    root: List[LaunchConfigurationTemplateID] = Field(..., max_length=200, min_length=0)


class LaunchDisposition(Enum):
    STOPPED = 'STOPPED'
    STARTED = 'STARTED'


class LaunchStatus(Enum):
    PENDING = 'PENDING'
    IN_PROGRESS = 'IN_PROGRESS'
    LAUNCHED = 'LAUNCHED'
    FAILED = 'FAILED'
    TERMINATED = 'TERMINATED'


class LaunchedInstance(BaseModel):
    ec2InstanceID: Optional[EC2InstanceID] = None
    firstBoot: Optional[FirstBoot] = None
    jobID: Optional[JobID] = None


class Licensing(BaseModel):
    osByol: Optional[Boolean] = None


class LifeCycleLastCutoverFinalized(BaseModel):
    apiCallDateTime: Optional[ISO8601DatetimeString] = None


class LifeCycleLastCutoverInitiated(BaseModel):
    apiCallDateTime: Optional[ISO8601DatetimeString] = None
    jobID: Optional[JobID] = None


class LifeCycleLastCutoverReverted(BaseModel):
    apiCallDateTime: Optional[ISO8601DatetimeString] = None


class LifeCycleLastTestFinalized(BaseModel):
    apiCallDateTime: Optional[ISO8601DatetimeString] = None


class LifeCycleLastTestInitiated(BaseModel):
    apiCallDateTime: Optional[ISO8601DatetimeString] = None
    jobID: Optional[JobID] = None


class LifeCycleLastTestReverted(BaseModel):
    apiCallDateTime: Optional[ISO8601DatetimeString] = None


class LifeCycleState(Enum):
    STOPPED = 'STOPPED'
    NOT_READY = 'NOT_READY'
    READY_FOR_TEST = 'READY_FOR_TEST'
    TESTING = 'TESTING'
    READY_FOR_CUTOVER = 'READY_FOR_CUTOVER'
    CUTTING_OVER = 'CUTTING_OVER'
    CUTOVER = 'CUTOVER'
    DISCONNECTED = 'DISCONNECTED'
    DISCOVERED = 'DISCOVERED'
    PENDING_INSTALLATION = 'PENDING_INSTALLATION'


class LifeCycleStates(RootModel[List[LifeCycleState]]):
    root: List[LifeCycleState] = Field(..., max_length=10, min_length=0)


class ListExportsRequestFiltersExportIDs(RootModel[List[ExportID]]):
    root: List[ExportID] = Field(..., max_length=10, min_length=0)


class ListImportsRequestFilters(BaseModel):
    importIDs: Optional[ImportIDsFilter] = None


class ListTagsForResourceRequest(BaseModel):
    pass


class MaxResultsType(RootModel[conint(ge=1, le=1000)]):
    root: conint(ge=1, le=1000)


class NetworkInterface(BaseModel):
    ips: Optional[IPsList] = None
    isPrimary: Optional[Boolean] = None
    macAddress: Optional[BoundedString] = None


class NetworkInterfaces(RootModel[List[NetworkInterface]]):
    root: List[NetworkInterface] = Field(..., max_length=32, min_length=0)


class OS(BaseModel):
    fullString: Optional[BoundedString] = None


class OperatingSystemString(RootModel[constr(pattern=r'^(linux|windows)$')]):
    root: constr(pattern=r'^(linux|windows)$')


class OrderType(RootModel[conint(ge=1001, le=10000)]):
    root: conint(ge=1001, le=10000)


class PaginationToken(RootModel[constr(min_length=0, max_length=2048)]):
    root: constr(min_length=0, max_length=2048)


class PositiveInteger(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class PostLaunchActionExecutionStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'


class PostLaunchActionsDeploymentType(Enum):
    TEST_AND_CUTOVER = 'TEST_AND_CUTOVER'
    CUTOVER_ONLY = 'CUTOVER_ONLY'
    TEST_ONLY = 'TEST_ONLY'


class RemoveSourceServerActionResponse(BaseModel):
    pass


class RemoveTemplateActionRequest(BaseModel):
    actionID: ActionID
    launchConfigurationTemplateID: LaunchConfigurationTemplateID


class RemoveTemplateActionResponse(BaseModel):
    pass


class ReplicationConfigurationDataPlaneRouting(Enum):
    PRIVATE_IP = 'PRIVATE_IP'
    PUBLIC_IP = 'PUBLIC_IP'


class ReplicationConfigurationDefaultLargeStagingDiskType(Enum):
    GP2 = 'GP2'
    ST1 = 'ST1'
    GP3 = 'GP3'


class ReplicationConfigurationEbsEncryption(Enum):
    DEFAULT = 'DEFAULT'
    CUSTOM = 'CUSTOM'


class ReplicationConfigurationReplicatedDiskStagingDiskType(Enum):
    AUTO = 'AUTO'
    GP2 = 'GP2'
    IO1 = 'IO1'
    SC1 = 'SC1'
    ST1 = 'ST1'
    STANDARD = 'STANDARD'
    GP3 = 'GP3'
    IO2 = 'IO2'


class ReplicationConfigurationTemplateID(
    RootModel[constr(pattern=r'^rct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)]
):
    root: constr(pattern=r'^rct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)


class ReplicationConfigurationTemplateIDs(
    RootModel[List[ReplicationConfigurationTemplateID]]
):
    root: List[ReplicationConfigurationTemplateID] = Field(
        ..., max_length=200, min_length=0
    )


class ReplicationType(Enum):
    AGENT_BASED = 'AGENT_BASED'
    SNAPSHOT_SHIPPING = 'SNAPSHOT_SHIPPING'


class ReplicationTypes(RootModel[List[ReplicationType]]):
    root: List[ReplicationType] = Field(..., max_length=2, min_length=0)


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class S3BucketName(RootModel[constr(pattern=r'^[a-zA-Z0-9.\-_]{1,255}$')]):
    root: constr(pattern=r'^[a-zA-Z0-9.\-_]{1,255}$')


class S3Key(RootModel[constr(pattern=r'^[^\x00]{1,1020}\.csv$')]):
    root: constr(pattern=r'^[^\x00]{1,1020}\.csv$')


class S3LogBucketName(RootModel[constr(min_length=3, max_length=63)]):
    root: constr(min_length=3, max_length=63)


class SecurityGroupID(
    RootModel[constr(pattern=r'^sg-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)]
):
    root: constr(pattern=r'^sg-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class SmallBoundedString(RootModel[constr(min_length=0, max_length=128)]):
    root: constr(min_length=0, max_length=128)


class SourceServerActionsRequestFilters(BaseModel):
    actionIDs: Optional[ActionIDs] = None


class SourceServerID(
    RootModel[constr(pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19)]
):
    root: constr(pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19)


class SsmDocumentName(
    RootModel[constr(pattern=r'^([A-Za-z0-9/:_\.-])+$', min_length=3, max_length=172)]
):
    root: constr(pattern=r'^([A-Za-z0-9/:_\.-])+$', min_length=3, max_length=172)


class SsmDocumentParameterName(
    RootModel[constr(pattern=r'^([A-Za-z0-9])+$', min_length=1, max_length=1011)]
):
    root: constr(pattern=r'^([A-Za-z0-9])+$', min_length=1, max_length=1011)


class SsmDocumentType(Enum):
    AUTOMATION = 'AUTOMATION'
    COMMAND = 'COMMAND'


class SsmExternalParameter(BaseModel):
    dynamicPath: Optional[JmesPathString] = None


class SsmParameterStoreParameterName(
    RootModel[constr(pattern=r'^([A-Za-z0-9_\.-])+$', min_length=1, max_length=1011)]
):
    root: constr(pattern=r'^([A-Za-z0-9_\.-])+$', min_length=1, max_length=1011)


class SsmParameterStoreParameterType(Enum):
    STRING = 'STRING'


class StartCutoverRequestSourceServerIDs(RootModel[List[SourceServerID]]):
    root: List[SourceServerID] = Field(..., max_length=200, min_length=1)


class StartExportRequest(BaseModel):
    s3Bucket: S3BucketName
    s3BucketOwner: Optional[AccountID] = None
    s3Key: S3Key


class StartReplicationRequest(BaseModel):
    sourceServerID: SourceServerID


class StartTestRequestSourceServerIDs(RootModel[List[SourceServerID]]):
    root: List[SourceServerID] = Field(..., max_length=200, min_length=1)


class StrictlyPositiveInteger(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class SubnetID(
    RootModel[constr(pattern=r'^subnet-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)]
):
    root: constr(pattern=r'^subnet-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)


class TagKey(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagValue(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class TagsMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TargetInstanceTypeRightSizingMethod(Enum):
    NONE = 'NONE'
    BASIC = 'BASIC'


class TemplateActionsRequestFilters(BaseModel):
    actionIDs: Optional[ActionIDs] = None


class TerminateTargetInstancesRequestSourceServerIDs(RootModel[List[SourceServerID]]):
    root: List[SourceServerID] = Field(..., max_length=200, min_length=1)


class ThrottlingException(RootModel[Any]):
    root: Any


class UnarchiveApplicationRequest(BaseModel):
    applicationID: ApplicationID


class UninitializedAccountException(RootModel[Any]):
    root: Any


class UntagResourceRequest(BaseModel):
    pass


class UpdateApplicationRequest(BaseModel):
    applicationID: ApplicationID
    description: Optional[ApplicationDescription] = None
    name: Optional[ApplicationName] = None


class UpdateSourceServerReplicationTypeRequest(BaseModel):
    replicationType: ReplicationType
    sourceServerID: SourceServerID


class ValidationException(RootModel[Any]):
    root: Any


class VcenterClientID(
    RootModel[constr(pattern=r'^vcc-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)]
):
    root: constr(pattern=r'^vcc-[0-9a-zA-Z]{17}$', min_length=21, max_length=21)


class VolumeType(Enum):
    io1 = 'io1'
    io2 = 'io2'
    gp3 = 'gp3'
    gp2 = 'gp2'
    st1 = 'st1'
    sc1 = 'sc1'
    standard = 'standard'


class WaveDescription(
    RootModel[constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)]
):
    root: constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)


class WaveHealthStatus(Enum):
    HEALTHY = 'HEALTHY'
    LAGGING = 'LAGGING'
    ERROR = 'ERROR'


class WaveID(
    RootModel[constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22)]
):
    root: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22)


class WaveIDsFilter(RootModel[List[WaveID]]):
    root: List[WaveID] = Field(..., max_length=200, min_length=0)


class WaveName(
    RootModel[
        constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)
    ]
):
    root: constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)


class WaveProgressStatus(Enum):
    NOT_STARTED = 'NOT_STARTED'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'


class ArchiveApplicationPostRequest(BaseModel):
    applicationID: constr(
        pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Application ID.')


class ArchiveWavePostRequest(BaseModel):
    waveID: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22) = (
        Field(..., description='Wave ID.')
    )


class AssociateApplicationsPostRequest(BaseModel):
    applicationIDs: List[ApplicationID] = Field(
        ..., description='Application IDs list.', max_length=50, min_length=1
    )
    waveID: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22) = (
        Field(..., description='Wave ID.')
    )


class AssociateSourceServersPostRequest(BaseModel):
    applicationID: constr(
        pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Application ID.')
    sourceServerIDs: List[SourceServerID] = Field(
        ..., description='Source server IDs list.', max_length=50, min_length=1
    )


class LifeCycle1(BaseModel):
    state: Optional[ChangeServerLifeCycleStateSourceServerLifecycleState] = None


class ChangeServerLifeCycleStatePostRequest(BaseModel):
    lifeCycle: LifeCycle1 = Field(
        ...,
        description='The request to change the source server migration lifecycle state.',
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ...,
        description='The request to change the source server migration lifecycle state by source server ID.',
    )


class CreateApplicationPostRequest(BaseModel):
    description: Optional[
        constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)
    ] = Field(None, description='Application description.')
    name: constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256) = (
        Field(..., description='Application name.')
    )
    tags: Optional[Dict[str, TagValue]] = Field(None, description='Application tags.')


class LargeVolumeConf(BaseModel):
    iops: Optional[PositiveInteger] = None
    throughput: Optional[PositiveInteger] = None
    volumeType: Optional[VolumeType] = None


class SmallVolumeConf(BaseModel):
    iops: Optional[PositiveInteger] = None
    throughput: Optional[PositiveInteger] = None
    volumeType: Optional[VolumeType] = None


class DataPlaneRouting(Enum):
    PRIVATE_IP = 'PRIVATE_IP'
    PUBLIC_IP = 'PUBLIC_IP'


class DefaultLargeStagingDiskType(Enum):
    GP2 = 'GP2'
    ST1 = 'ST1'
    GP3 = 'GP3'


class EbsEncryption(Enum):
    DEFAULT = 'DEFAULT'
    CUSTOM = 'CUSTOM'


class CreateReplicationConfigurationTemplatePostRequest(BaseModel):
    associateDefaultSecurityGroup: bool = Field(
        ...,
        description='Request to associate the default Application Migration Service Security group with the Replication Settings template.',
    )
    bandwidthThrottling: conint(ge=0) = Field(
        ...,
        description='Request to configure bandwidth throttling during Replication Settings template creation.',
    )
    createPublicIP: bool = Field(
        ...,
        description='Request to create Public IP during Replication Settings template creation.',
    )
    dataPlaneRouting: DataPlaneRouting = Field(
        ...,
        description='Request to configure data plane routing during Replication Settings template creation.',
    )
    defaultLargeStagingDiskType: DefaultLargeStagingDiskType = Field(
        ...,
        description='Request to configure the default large staging disk EBS volume type during Replication Settings template creation.',
    )
    ebsEncryption: EbsEncryption = Field(
        ...,
        description='Request to configure EBS encryption during Replication Settings template creation.',
    )
    ebsEncryptionKeyArn: Optional[constr(min_length=20, max_length=2048)] = Field(
        None,
        description='Request to configure an EBS encryption key during Replication Settings template creation.',
    )
    replicationServerInstanceType: constr(min_length=0, max_length=255) = Field(
        ...,
        description='Request to configure the Replication Server instance type during Replication Settings template creation.',
    )
    replicationServersSecurityGroupsIDs: List[SecurityGroupID] = Field(
        ...,
        description='Request to configure the Replication Server Security group ID during Replication Settings template creation.',
        max_length=32,
        min_length=0,
    )
    stagingAreaSubnetId: constr(
        pattern=r'^subnet-[0-9a-fA-F]{8,}$', min_length=0, max_length=255
    ) = Field(
        ...,
        description='Request to configure the Staging Area subnet ID during Replication Settings template creation.',
    )
    stagingAreaTags: Dict[str, TagValue] = Field(
        ...,
        description='Request to configure Staging Area tags during Replication Settings template creation.',
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='Request to configure tags during Replication Settings template creation.',
    )
    useDedicatedReplicationServer: bool = Field(
        ...,
        description='Request to use Dedicated Replication Servers during Replication Settings template creation.',
    )


class CreateWavePostRequest(BaseModel):
    description: Optional[
        constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)
    ] = Field(None, description='Wave description.')
    name: constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256) = (
        Field(..., description='Wave name.')
    )
    tags: Optional[Dict[str, TagValue]] = Field(None, description='Wave tags.')


class DeleteApplicationPostRequest(BaseModel):
    applicationID: constr(
        pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Application ID.')


class DeleteJobPostRequest(BaseModel):
    jobID: constr(pattern=r'^mgnjob-[0-9a-zA-Z]{17}$', min_length=24, max_length=24) = (
        Field(..., description='Request to delete Job from service by Job ID.')
    )


class DeleteLaunchConfigurationTemplatePostRequest(BaseModel):
    launchConfigurationTemplateID: constr(
        pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='ID of resource to be deleted.')


class DeleteReplicationConfigurationTemplatePostRequest(BaseModel):
    replicationConfigurationTemplateID: constr(
        pattern=r'^rct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(
        ...,
        description='Request to delete Replication Configuration Template from service by Replication Configuration Template ID.',
    )


class DeleteSourceServerPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ..., description='Request to delete Source Server from service by Server ID.'
    )


class DeleteVcenterClientPostRequest(BaseModel):
    vcenterClientID: constr(
        pattern=r'^vcc-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='ID of resource to be deleted.')


class DeleteWavePostRequest(BaseModel):
    waveID: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22) = (
        Field(..., description='Wave ID.')
    )


class DescribeJobLogItemsPostRequest(BaseModel):
    jobID: constr(pattern=r'^mgnjob-[0-9a-zA-Z]{17}$', min_length=24, max_length=24) = (
        Field(..., description='Request to describe Job log job ID.')
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='Request to describe Job log item maximum results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='Request to describe Job log next token.'
    )


class DescribeLaunchConfigurationTemplatesPostRequest(BaseModel):
    launchConfigurationTemplateIDs: Optional[List[LaunchConfigurationTemplateID]] = (
        Field(
            None,
            description='Request to filter Launch Configuration Templates list by Launch Configuration Template ID.',
            max_length=200,
            min_length=0,
        )
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None,
        description='Maximum results to be returned in DescribeLaunchConfigurationTemplates.',
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None,
        description='Next pagination token returned from DescribeLaunchConfigurationTemplates.',
    )


class DescribeReplicationConfigurationTemplatesPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None,
        description='Request to describe Replication Configuration template by max results.',
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None,
        description='Request to describe Replication Configuration template by next token.',
    )
    replicationConfigurationTemplateIDs: Optional[
        List[ReplicationConfigurationTemplateID]
    ] = Field(
        None,
        description='Request to describe Replication Configuration template by template IDs.',
        max_length=200,
        min_length=0,
    )


class DisassociateApplicationsPostRequest(BaseModel):
    applicationIDs: List[ApplicationID] = Field(
        ..., description='Application IDs list.', max_length=50, min_length=1
    )
    waveID: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22) = (
        Field(..., description='Wave ID.')
    )


class DisassociateSourceServersPostRequest(BaseModel):
    applicationID: constr(
        pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Application ID.')
    sourceServerIDs: List[SourceServerID] = Field(
        ..., description='Source server IDs list.', max_length=50, min_length=1
    )


class DisconnectFromServicePostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ...,
        description='Request to disconnect Source Server from service by Server ID.',
    )


class FinalizeCutoverPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(..., description='Request to finalize Cutover by Source Server ID.')


class GetLaunchConfigurationPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ...,
        description='Request to get Launch Configuration information by Source Server ID.',
    )


class GetReplicationConfigurationPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ..., description='Request to get Replication Configuration by Source Server ID.'
    )


class Filters2(BaseModel):
    applicationIDs: Optional[ApplicationIDsFilter] = None
    isArchived: Optional[Boolean] = None
    waveIDs: Optional[WaveIDsFilter] = None


class ListApplicationsPostRequest(BaseModel):
    filters: Optional[Filters2] = Field(None, description='Applications list filters.')
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='Maximum results to return when listing applications.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='Request next token.'
    )


class ListExportErrorsPostRequest(BaseModel):
    exportID: constr(
        pattern=r'^export-[0-9a-zA-Z]{17}$', min_length=24, max_length=24
    ) = Field(..., description='List export errors request export id.')
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='List export errors request max results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='List export errors request next token.'
    )


class Filters3(BaseModel):
    exportIDs: Optional[ListExportsRequestFiltersExportIDs] = None


class ListExportsPostRequest(BaseModel):
    filters: Optional[Filters3] = Field(
        None, description='List exports request filters.'
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='List export request max results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='List export request next token.'
    )


class ListImportErrorsPostRequest(BaseModel):
    importID: constr(
        pattern=r'^import-[0-9a-zA-Z]{17}$', min_length=24, max_length=24
    ) = Field(..., description='List import errors request import id.')
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='List import errors request max results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='List import errors request next token.'
    )


class Filters4(BaseModel):
    importIDs: Optional[ImportIDsFilter] = None


class ListImportsPostRequest(BaseModel):
    filters: Optional[Filters4] = Field(
        None, description='List imports request filters.'
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='List imports request max results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='List imports request next token.'
    )


class Filters5(BaseModel):
    actionIDs: Optional[ActionIDs] = None


class ListSourceServerActionsPostRequest(BaseModel):
    filters: Optional[Filters5] = Field(
        None, description='Source server post migration custom action filters.'
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None,
        description='Maximum amount of items to return when listing source server post migration custom actions.',
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None,
        description='Next token to use when listing source server post migration custom actions.',
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(..., description='Source server ID.')


class ListTemplateActionsPostRequest(BaseModel):
    filters: Optional[Filters5] = Field(
        None, description='Template post migration custom action filters.'
    )
    launchConfigurationTemplateID: constr(
        pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Launch configuration template ID.')
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None,
        description='Maximum amount of items to return when listing template post migration custom actions.',
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None,
        description='Next token to use when listing template post migration custom actions.',
    )


class Filters7(BaseModel):
    isArchived: Optional[Boolean] = None
    waveIDs: Optional[WaveIDsFilter] = None


class ListWavesPostRequest(BaseModel):
    filters: Optional[Filters7] = Field(None, description='Waves list filters.')
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='Maximum results to return when listing waves.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='Request next token.'
    )


class MarkAsArchivedPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(..., description='Mark as archived by Source Server ID.')


class Category(Enum):
    DISASTER_RECOVERY = 'DISASTER_RECOVERY'
    OPERATING_SYSTEM = 'OPERATING_SYSTEM'
    LICENSE_AND_SUBSCRIPTION = 'LICENSE_AND_SUBSCRIPTION'
    VALIDATION = 'VALIDATION'
    OBSERVABILITY = 'OBSERVABILITY'
    SECURITY = 'SECURITY'
    NETWORKING = 'NETWORKING'
    CONFIGURATION = 'CONFIGURATION'
    BACKUP = 'BACKUP'
    OTHER = 'OTHER'


class RemoveSourceServerActionPostRequest(BaseModel):
    actionID: constr(pattern=r'[0-9a-zA-Z]$', min_length=1, max_length=64) = Field(
        ..., description='Source server post migration custom action ID to remove.'
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ...,
        description='Source server ID of the post migration custom action to remove.',
    )


class RemoveTemplateActionPostRequest(BaseModel):
    actionID: constr(pattern=r'[0-9a-zA-Z]$', min_length=1, max_length=64) = Field(
        ..., description='Template post migration custom action ID to remove.'
    )
    launchConfigurationTemplateID: constr(
        pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(
        ...,
        description='Launch configuration template ID of the post migration custom action to remove.',
    )


class RetryDataReplicationPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(..., description='Retry data replication for Source Server ID.')


class StartCutoverPostRequest(BaseModel):
    sourceServerIDs: List[SourceServerID] = Field(
        ...,
        description='Start Cutover by Source Server IDs.',
        max_length=200,
        min_length=1,
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None, description='Start Cutover by Tags.'
    )


class StartExportPostRequest(BaseModel):
    s3Bucket: constr(pattern=r'^[a-zA-Z0-9.\-_]{1,255}$') = Field(
        ..., description='Start export request s3 bucket.'
    )
    s3BucketOwner: Optional[
        constr(pattern=r'[0-9]{12,}', min_length=12, max_length=12)
    ] = Field(None, description='Start export request s3 bucket owner.')
    s3Key: constr(pattern=r'^[^\x00]{1,1020}\.csv$') = Field(
        ..., description='Start export request s3key.'
    )


class S3BucketSource1(BaseModel):
    s3Bucket: Optional[S3BucketName] = None
    s3BucketOwner: Optional[AccountID] = None
    s3Key: Optional[S3Key] = None


class StartImportPostRequest(BaseModel):
    clientToken: Optional[constr(min_length=0, max_length=64)] = Field(
        None, description='Start import request client token.'
    )
    s3BucketSource: S3BucketSource1 = Field(..., description='S3 bucket source.')


class StartReplicationPostRequest(BaseModel):
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(..., description='ID of source server on which to start replication.')


class StartTestPostRequest(BaseModel):
    sourceServerIDs: List[SourceServerID] = Field(
        ...,
        description='Start Test for Source Server IDs.',
        max_length=200,
        min_length=1,
    )
    tags: Optional[Dict[str, TagValue]] = Field(None, description='Start Test by Tags.')


class TerminateTargetInstancesPostRequest(BaseModel):
    sourceServerIDs: List[SourceServerID] = Field(
        ...,
        description='Terminate Target instance by Source Server IDs.',
        max_length=200,
        min_length=1,
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None, description='Terminate Target instance by Tags.'
    )


class UnarchiveApplicationPostRequest(BaseModel):
    applicationID: constr(
        pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Application ID.')


class UnarchiveWavePostRequest(BaseModel):
    waveID: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22) = (
        Field(..., description='Wave ID.')
    )


class UpdateApplicationPostRequest(BaseModel):
    applicationID: constr(
        pattern=r'^app-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Application ID.')
    description: Optional[
        constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)
    ] = Field(None, description='Application description.')
    name: Optional[
        constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)
    ] = Field(None, description='Application name.')


class UpdateReplicationConfigurationTemplatePostRequest(BaseModel):
    arn: Optional[constr(min_length=20, max_length=2048)] = Field(
        None, description='Update replication configuration template ARN request.'
    )
    associateDefaultSecurityGroup: Optional[bool] = Field(
        None,
        description='Update replication configuration template associate default Application Migration Service Security group request.',
    )
    bandwidthThrottling: Optional[conint(ge=0)] = Field(
        None,
        description='Update replication configuration template bandwidth throttling request.',
    )
    createPublicIP: Optional[bool] = Field(
        None,
        description='Update replication configuration template create Public IP request.',
    )
    dataPlaneRouting: Optional[DataPlaneRouting] = Field(
        None,
        description='Update replication configuration template data plane routing request.',
    )
    defaultLargeStagingDiskType: Optional[DefaultLargeStagingDiskType] = Field(
        None,
        description='Update replication configuration template use default large Staging Disk type request.',
    )
    ebsEncryption: Optional[EbsEncryption] = Field(
        None,
        description='Update replication configuration template EBS encryption request.',
    )
    ebsEncryptionKeyArn: Optional[constr(min_length=20, max_length=2048)] = Field(
        None,
        description='Update replication configuration template EBS encryption key ARN request.',
    )
    replicationConfigurationTemplateID: constr(
        pattern=r'^rct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(
        ...,
        description='Update replication configuration template template ID request.',
    )
    replicationServerInstanceType: Optional[constr(min_length=0, max_length=255)] = (
        Field(
            None,
            description='Update replication configuration template Replication Server instance type request.',
        )
    )
    replicationServersSecurityGroupsIDs: Optional[List[SecurityGroupID]] = Field(
        None,
        description='Update replication configuration template Replication Server Security groups IDs request.',
        max_length=32,
        min_length=0,
    )
    stagingAreaSubnetId: Optional[
        constr(pattern=r'^subnet-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)
    ] = Field(
        None,
        description='Update replication configuration template Staging Area subnet ID request.',
    )
    stagingAreaTags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='Update replication configuration template Staging Area Tags request.',
    )
    useDedicatedReplicationServer: Optional[bool] = Field(
        None,
        description='Update replication configuration template use dedicated Replication Server request.',
    )


class UpdateSourceServerReplicationTypePostRequest(BaseModel):
    replicationType: ReplicationType = Field(
        ..., description='Replication type to which to update source server.'
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ..., description='ID of source server on which to update replication type.'
    )


class UpdateWavePostRequest(BaseModel):
    description: Optional[
        constr(pattern=r'^[^\x00]*$', min_length=0, max_length=600)
    ] = Field(None, description='Wave description.')
    name: Optional[
        constr(pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256)
    ] = Field(None, description='Wave name.')
    waveID: constr(pattern=r'^wave-[0-9a-zA-Z]{17}$', min_length=22, max_length=22) = (
        Field(..., description='Wave ID.')
    )


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, TagValue] = Field(..., description='Tag resource by Tags.')


class ApplicationAggregatedStatus(BaseModel):
    healthStatus: Optional[ApplicationHealthStatus] = None
    lastUpdateDateTime: Optional[ISO8601DatetimeString] = None
    progressStatus: Optional[ApplicationProgressStatus] = None
    totalSourceServers: Optional[PositiveInteger] = None


class ArchiveWaveRequest(BaseModel):
    waveID: WaveID


class AssociateApplicationsRequest(BaseModel):
    applicationIDs: ApplicationIDs
    waveID: WaveID


class AssociateSourceServersRequestSourceServerIDs(RootModel[List[SourceServerID]]):
    root: List[SourceServerID] = Field(..., max_length=50, min_length=1)


class CPU(BaseModel):
    cores: Optional[PositiveInteger] = None
    modelName: Optional[BoundedString] = None


class ChangeServerLifeCycleStateSourceServerLifecycle(BaseModel):
    state: ChangeServerLifeCycleStateSourceServerLifecycleState


class Cpus(RootModel[List[CPU]]):
    root: List[CPU] = Field(..., max_length=256, min_length=0)


class CreateApplicationRequest(BaseModel):
    description: Optional[ApplicationDescription] = None
    name: ApplicationName
    tags: Optional[TagsMap] = None


class CreateWaveRequest(BaseModel):
    description: Optional[WaveDescription] = None
    name: WaveName
    tags: Optional[TagsMap] = None


class DataReplicationError(BaseModel):
    error: Optional[DataReplicationErrorString] = None
    rawError: Optional[LargeBoundedString] = None


class DataReplicationInfoReplicatedDisk(BaseModel):
    backloggedStorageBytes: Optional[PositiveInteger] = None
    deviceName: Optional[BoundedString] = None
    replicatedStorageBytes: Optional[PositiveInteger] = None
    rescannedStorageBytes: Optional[PositiveInteger] = None
    totalStorageBytes: Optional[PositiveInteger] = None


class DataReplicationInfoReplicatedDisks(
    RootModel[List[DataReplicationInfoReplicatedDisk]]
):
    root: List[DataReplicationInfoReplicatedDisk] = Field(
        ..., max_length=60, min_length=0
    )


class DataReplicationInitiationStep(BaseModel):
    name: Optional[DataReplicationInitiationStepName] = None
    status: Optional[DataReplicationInitiationStepStatus] = None


class DataReplicationInitiationSteps(RootModel[List[DataReplicationInitiationStep]]):
    root: List[DataReplicationInitiationStep]


class DeleteJobRequest(BaseModel):
    jobID: JobID


class DeleteLaunchConfigurationTemplateRequest(BaseModel):
    launchConfigurationTemplateID: LaunchConfigurationTemplateID


class DeleteReplicationConfigurationTemplateRequest(BaseModel):
    replicationConfigurationTemplateID: ReplicationConfigurationTemplateID


class DeleteSourceServerRequest(BaseModel):
    sourceServerID: SourceServerID


class DeleteVcenterClientRequest(BaseModel):
    vcenterClientID: VcenterClientID


class DeleteWaveRequest(BaseModel):
    waveID: WaveID


class DescribeJobLogItemsRequest(BaseModel):
    jobID: JobID
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class DescribeJobsRequestFiltersJobIDs(RootModel[List[JobID]]):
    root: List[JobID] = Field(..., max_length=1000, min_length=0)


class DescribeLaunchConfigurationTemplatesRequest(BaseModel):
    launchConfigurationTemplateIDs: Optional[LaunchConfigurationTemplateIDs] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class DescribeReplicationConfigurationTemplatesRequest(BaseModel):
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None
    replicationConfigurationTemplateIDs: Optional[
        ReplicationConfigurationTemplateIDs
    ] = None


class DescribeSourceServersRequestFiltersIDs(RootModel[List[SourceServerID]]):
    root: List[SourceServerID] = Field(..., max_length=200, min_length=0)


class DisassociateApplicationsRequest(BaseModel):
    applicationIDs: ApplicationIDs
    waveID: WaveID


class DisassociateSourceServersRequestSourceServerIDs(RootModel[List[SourceServerID]]):
    root: List[SourceServerID] = Field(..., max_length=50, min_length=1)


class DisconnectFromServiceRequest(BaseModel):
    sourceServerID: SourceServerID


class Disk(BaseModel):
    bytes: Optional[PositiveInteger] = None
    deviceName: Optional[BoundedString] = None


class Disks(RootModel[List[Disk]]):
    root: List[Disk] = Field(..., max_length=1000, min_length=0)


class ExportErrorData(BaseModel):
    rawError: Optional[LargeBoundedString] = None


class ExportTaskError(BaseModel):
    errorData: Optional[ExportErrorData] = None
    errorDateTime: Optional[ISO8601DatetimeString] = None


class ExportTaskSummary(BaseModel):
    applicationsCount: Optional[PositiveInteger] = None
    serversCount: Optional[PositiveInteger] = None
    wavesCount: Optional[PositiveInteger] = None


class FinalizeCutoverRequest(BaseModel):
    sourceServerID: SourceServerID


class GetLaunchConfigurationRequest(BaseModel):
    sourceServerID: SourceServerID


class GetReplicationConfigurationRequest(BaseModel):
    sourceServerID: SourceServerID


class ImportErrorData(BaseModel):
    applicationID: Optional[ApplicationID] = None
    ec2LaunchTemplateID: Optional[BoundedString] = None
    rawError: Optional[LargeBoundedString] = None
    rowNumber: Optional[PositiveInteger] = None
    sourceServerID: Optional[SourceServerID] = None
    waveID: Optional[WaveID] = None


class ImportTaskError(BaseModel):
    errorData: Optional[ImportErrorData] = None
    errorDateTime: Optional[ISO8601DatetimeString] = None
    errorType: Optional[ImportErrorType] = None


class ImportTaskSummaryApplications(BaseModel):
    createdCount: Optional[PositiveInteger] = None
    modifiedCount: Optional[PositiveInteger] = None


class ImportTaskSummaryServers(BaseModel):
    createdCount: Optional[PositiveInteger] = None
    modifiedCount: Optional[PositiveInteger] = None


class ImportTaskSummaryWaves(BaseModel):
    createdCount: Optional[PositiveInteger] = None
    modifiedCount: Optional[PositiveInteger] = None


class JobLogEventData(BaseModel):
    conversionServerID: Optional[EC2InstanceID] = None
    rawError: Optional[LargeBoundedString] = None
    sourceServerID: Optional[SourceServerID] = None
    targetInstanceID: Optional[EC2InstanceID] = None


class LaunchTemplateDiskConf(BaseModel):
    iops: Optional[PositiveInteger] = None
    throughput: Optional[PositiveInteger] = None
    volumeType: Optional[VolumeType] = None


class LifeCycleLastCutover(BaseModel):
    finalized: Optional[LifeCycleLastCutoverFinalized] = None
    initiated: Optional[LifeCycleLastCutoverInitiated] = None
    reverted: Optional[LifeCycleLastCutoverReverted] = None


class LifeCycleLastTest(BaseModel):
    finalized: Optional[LifeCycleLastTestFinalized] = None
    initiated: Optional[LifeCycleLastTestInitiated] = None
    reverted: Optional[LifeCycleLastTestReverted] = None


class ListApplicationsRequestFilters(BaseModel):
    applicationIDs: Optional[ApplicationIDsFilter] = None
    isArchived: Optional[Boolean] = None
    waveIDs: Optional[WaveIDsFilter] = None


class ListExportErrorsRequest(BaseModel):
    exportID: ExportID
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ListExportsRequestFilters(BaseModel):
    exportIDs: Optional[ListExportsRequestFiltersExportIDs] = None


class ListImportErrorsRequest(BaseModel):
    importID: ImportID
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ListImportsRequest(BaseModel):
    filters: Optional[ListImportsRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ListSourceServerActionsRequest(BaseModel):
    filters: Optional[SourceServerActionsRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None
    sourceServerID: SourceServerID


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagsMap] = None


class ListTemplateActionsRequest(BaseModel):
    filters: Optional[TemplateActionsRequestFilters] = None
    launchConfigurationTemplateID: LaunchConfigurationTemplateID
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ListWavesRequestFilters(BaseModel):
    isArchived: Optional[Boolean] = None
    waveIDs: Optional[WaveIDsFilter] = None


class MarkAsArchivedRequest(BaseModel):
    sourceServerID: SourceServerID


class RemoveSourceServerActionRequest(BaseModel):
    actionID: ActionID
    sourceServerID: SourceServerID


class ReplicationConfigurationReplicatedDisk(BaseModel):
    deviceName: Optional[BoundedString] = None
    iops: Optional[PositiveInteger] = None
    isBootDisk: Optional[Boolean] = None
    stagingDiskType: Optional[ReplicationConfigurationReplicatedDiskStagingDiskType] = (
        None
    )
    throughput: Optional[PositiveInteger] = None


class ReplicationConfigurationReplicatedDisks(
    RootModel[List[ReplicationConfigurationReplicatedDisk]]
):
    root: List[ReplicationConfigurationReplicatedDisk] = Field(
        ..., max_length=60, min_length=0
    )


class ReplicationServersSecurityGroupsIDs(RootModel[List[SecurityGroupID]]):
    root: List[SecurityGroupID] = Field(..., max_length=32, min_length=0)


class RetryDataReplicationRequest(BaseModel):
    sourceServerID: SourceServerID


class S3BucketSource(BaseModel):
    s3Bucket: S3BucketName
    s3BucketOwner: Optional[AccountID] = None
    s3Key: S3Key


class SourceProperties(BaseModel):
    cpus: Optional[Cpus] = None
    disks: Optional[Disks] = None
    identificationHints: Optional[IdentificationHints] = None
    lastUpdatedDateTime: Optional[ISO8601DatetimeString] = None
    networkInterfaces: Optional[NetworkInterfaces] = None
    os: Optional[OS] = None
    ramBytes: Optional[PositiveInteger] = None
    recommendedInstanceType: Optional[EC2InstanceType] = None


class SsmDocumentExternalParameters(
    RootModel[Optional[Dict[str, SsmExternalParameter]]]
):
    root: Optional[Dict[str, SsmExternalParameter]] = None


class SsmParameterStoreParameter(BaseModel):
    parameterName: SsmParameterStoreParameterName
    parameterType: SsmParameterStoreParameterType


class SsmParameterStoreParameters(RootModel[List[SsmParameterStoreParameter]]):
    root: List[SsmParameterStoreParameter] = Field(..., max_length=10, min_length=0)


class StartCutoverRequest(BaseModel):
    sourceServerIDs: StartCutoverRequestSourceServerIDs
    tags: Optional[TagsMap] = None


class StartImportRequest(BaseModel):
    clientToken: Optional[ClientIdempotencyToken] = None
    s3BucketSource: S3BucketSource


class StartTestRequest(BaseModel):
    sourceServerIDs: StartTestRequestSourceServerIDs
    tags: Optional[TagsMap] = None


class TagResourceRequest(BaseModel):
    tags: TagsMap


class TerminateTargetInstancesRequest(BaseModel):
    sourceServerIDs: TerminateTargetInstancesRequestSourceServerIDs
    tags: Optional[TagsMap] = None


class UnarchiveWaveRequest(BaseModel):
    waveID: WaveID


class UpdateReplicationConfigurationRequest(BaseModel):
    associateDefaultSecurityGroup: Optional[Boolean] = None
    bandwidthThrottling: Optional[PositiveInteger] = None
    createPublicIP: Optional[Boolean] = None
    dataPlaneRouting: Optional[ReplicationConfigurationDataPlaneRouting] = None
    defaultLargeStagingDiskType: Optional[
        ReplicationConfigurationDefaultLargeStagingDiskType
    ] = None
    ebsEncryption: Optional[ReplicationConfigurationEbsEncryption] = None
    ebsEncryptionKeyArn: Optional[ARN] = None
    name: Optional[SmallBoundedString] = None
    replicatedDisks: Optional[ReplicationConfigurationReplicatedDisks] = None
    replicationServerInstanceType: Optional[EC2InstanceType] = None
    replicationServersSecurityGroupsIDs: Optional[
        ReplicationServersSecurityGroupsIDs
    ] = None
    sourceServerID: SourceServerID
    stagingAreaSubnetId: Optional[SubnetID] = None
    stagingAreaTags: Optional[TagsMap] = None
    useDedicatedReplicationServer: Optional[Boolean] = None


class UpdateReplicationConfigurationTemplateRequest(BaseModel):
    arn: Optional[ARN] = None
    associateDefaultSecurityGroup: Optional[Boolean] = None
    bandwidthThrottling: Optional[PositiveInteger] = None
    createPublicIP: Optional[Boolean] = None
    dataPlaneRouting: Optional[ReplicationConfigurationDataPlaneRouting] = None
    defaultLargeStagingDiskType: Optional[
        ReplicationConfigurationDefaultLargeStagingDiskType
    ] = None
    ebsEncryption: Optional[ReplicationConfigurationEbsEncryption] = None
    ebsEncryptionKeyArn: Optional[ARN] = None
    replicationConfigurationTemplateID: ReplicationConfigurationTemplateID
    replicationServerInstanceType: Optional[EC2InstanceType] = None
    replicationServersSecurityGroupsIDs: Optional[
        ReplicationServersSecurityGroupsIDs
    ] = None
    stagingAreaSubnetId: Optional[SubnetID] = None
    stagingAreaTags: Optional[TagsMap] = None
    useDedicatedReplicationServer: Optional[Boolean] = None


class UpdateWaveRequest(BaseModel):
    description: Optional[WaveDescription] = None
    name: Optional[WaveName] = None
    waveID: WaveID


class VcenterClient(BaseModel):
    arn: Optional[ARN] = None
    datacenterName: Optional[BoundedString] = None
    hostname: Optional[BoundedString] = None
    lastSeenDatetime: Optional[ISO8601DatetimeString] = None
    sourceServerTags: Optional[TagsMap] = None
    tags: Optional[TagsMap] = None
    vcenterClientID: Optional[VcenterClientID] = None
    vcenterUUID: Optional[BoundedString] = None


class VcenterClientList(RootModel[List[VcenterClient]]):
    root: List[VcenterClient]


class WaveAggregatedStatus(BaseModel):
    healthStatus: Optional[WaveHealthStatus] = None
    lastUpdateDateTime: Optional[ISO8601DatetimeString] = None
    progressStatus: Optional[WaveProgressStatus] = None
    replicationStartedDateTime: Optional[ISO8601DatetimeString] = None
    totalApplications: Optional[PositiveInteger] = None


class Filters(BaseModel):
    fromDate: Optional[ISO8601DatetimeString] = None
    jobIDs: Optional[DescribeJobsRequestFiltersJobIDs] = None
    toDate: Optional[ISO8601DatetimeString] = None


class DescribeJobsPostRequest(BaseModel):
    filters: Optional[Filters] = Field(
        None, description='Request to describe Job log filters.'
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='Request to describe job log items by max results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='Request to describe job log items by next token.'
    )


class Filters1(BaseModel):
    applicationIDs: Optional[DescribeSourceServersRequestApplicationIDs] = None
    isArchived: Optional[Boolean] = None
    lifeCycleStates: Optional[LifeCycleStates] = None
    replicationTypes: Optional[ReplicationTypes] = None
    sourceServerIDs: Optional[DescribeSourceServersRequestFiltersIDs] = None


class DescribeSourceServersPostRequest(BaseModel):
    filters: Optional[Filters1] = Field(
        None, description='Request to filter Source Servers list.'
    )
    maxResults: Optional[conint(ge=1, le=1000)] = Field(
        None, description='Request to filter Source Servers list by maximum results.'
    )
    nextToken: Optional[constr(min_length=0, max_length=2048)] = Field(
        None, description='Request to filter Source Servers list by next token.'
    )


class PutSourceServerActionPostRequest(BaseModel):
    actionID: constr(pattern=r'[0-9a-zA-Z]$', min_length=1, max_length=64) = Field(
        ..., description='Source server post migration custom action ID.'
    )
    actionName: constr(
        pattern=r'^[^\s\x00]( *[^\s\x00])*$', min_length=1, max_length=256
    ) = Field(..., description='Source server post migration custom action name.')
    active: Optional[bool] = Field(
        None, description='Source server post migration custom action active status.'
    )
    category: Optional[Category] = Field(
        None, description='Source server post migration custom action category.'
    )
    description: Optional[
        constr(pattern=r'^[0-9a-zA-Z ():/.,\'-_#*; ]*$', min_length=0, max_length=256)
    ] = Field(
        None, description='Source server post migration custom action description.'
    )
    documentIdentifier: constr(min_length=0, max_length=256) = Field(
        ...,
        description='Source server post migration custom action document identifier.',
    )
    documentVersion: Optional[constr(pattern=r'^(\$DEFAULT|\$LATEST|[0-9]+)$')] = Field(
        None, description='Source server post migration custom action document version.'
    )
    externalParameters: Optional[Dict[str, SsmExternalParameter]] = Field(
        None,
        description='Source server post migration custom action external parameters.',
    )
    mustSucceedForCutover: Optional[bool] = Field(
        None,
        description='Source server post migration custom action must succeed for cutover.',
    )
    order: conint(ge=1001, le=10000) = Field(
        ..., description='Source server post migration custom action order.'
    )
    parameters: Optional[Dict[str, SsmParameterStoreParameters]] = Field(
        None, description='Source server post migration custom action parameters.'
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(..., description='Source server ID.')
    timeoutSeconds: Optional[conint(ge=1)] = Field(
        None,
        description='Source server post migration custom action timeout in seconds.',
    )


class PutTemplateActionPostRequest(BaseModel):
    actionID: constr(pattern=r'[0-9a-zA-Z]$', min_length=1, max_length=64) = Field(
        ..., description='Template post migration custom action ID.'
    )
    actionName: constr(min_length=0, max_length=256) = Field(
        ..., description='Template post migration custom action name.'
    )
    active: Optional[bool] = Field(
        None, description='Template post migration custom action active status.'
    )
    category: Optional[Category] = Field(
        None, description='Template post migration custom action category.'
    )
    description: Optional[
        constr(pattern=r'^[0-9a-zA-Z ():/.,\'-_#*; ]*$', min_length=0, max_length=256)
    ] = Field(None, description='Template post migration custom action description.')
    documentIdentifier: constr(min_length=0, max_length=256) = Field(
        ..., description='Template post migration custom action document identifier.'
    )
    documentVersion: Optional[constr(pattern=r'^(\$DEFAULT|\$LATEST|[0-9]+)$')] = Field(
        None, description='Template post migration custom action document version.'
    )
    externalParameters: Optional[Dict[str, SsmExternalParameter]] = Field(
        None, description='Template post migration custom action external parameters.'
    )
    launchConfigurationTemplateID: constr(
        pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Launch configuration template ID.')
    mustSucceedForCutover: Optional[bool] = Field(
        None,
        description='Template post migration custom action must succeed for cutover.',
    )
    operatingSystem: Optional[constr(pattern=r'^(linux|windows)$')] = Field(
        None,
        description='Operating system eligible for this template post migration custom action.',
    )
    order: conint(ge=1001, le=10000) = Field(
        ..., description='Template post migration custom action order.'
    )
    parameters: Optional[Dict[str, SsmParameterStoreParameters]] = Field(
        None, description='Template post migration custom action parameters.'
    )
    timeoutSeconds: Optional[conint(ge=1)] = Field(
        None, description='Template post migration custom action timeout in seconds.'
    )


class UpdateReplicationConfigurationPostRequest(BaseModel):
    associateDefaultSecurityGroup: Optional[bool] = Field(
        None,
        description='Update replication configuration associate default Application Migration Service Security group request.',
    )
    bandwidthThrottling: Optional[conint(ge=0)] = Field(
        None,
        description='Update replication configuration bandwidth throttling request.',
    )
    createPublicIP: Optional[bool] = Field(
        None, description='Update replication configuration create Public IP request.'
    )
    dataPlaneRouting: Optional[DataPlaneRouting] = Field(
        None, description='Update replication configuration data plane routing request.'
    )
    defaultLargeStagingDiskType: Optional[DefaultLargeStagingDiskType] = Field(
        None,
        description='Update replication configuration use default large Staging Disk type request.',
    )
    ebsEncryption: Optional[EbsEncryption] = Field(
        None, description='Update replication configuration EBS encryption request.'
    )
    ebsEncryptionKeyArn: Optional[constr(min_length=20, max_length=2048)] = Field(
        None,
        description='Update replication configuration EBS encryption key ARN request.',
    )
    name: Optional[constr(min_length=0, max_length=128)] = Field(
        None, description='Update replication configuration name request.'
    )
    replicatedDisks: Optional[List[ReplicationConfigurationReplicatedDisk]] = Field(
        None,
        description='Update replication configuration replicated disks request.',
        max_length=60,
        min_length=0,
    )
    replicationServerInstanceType: Optional[constr(min_length=0, max_length=255)] = (
        Field(
            None,
            description='Update replication configuration Replication Server instance type request.',
        )
    )
    replicationServersSecurityGroupsIDs: Optional[List[SecurityGroupID]] = Field(
        None,
        description='Update replication configuration Replication Server Security Groups IDs request.',
        max_length=32,
        min_length=0,
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ..., description='Update replication configuration Source Server ID request.'
    )
    stagingAreaSubnetId: Optional[
        constr(pattern=r'^subnet-[0-9a-fA-F]{8,}$', min_length=0, max_length=255)
    ] = Field(
        None,
        description='Update replication configuration Staging Area subnet request.',
    )
    stagingAreaTags: Optional[Dict[str, TagValue]] = Field(
        None, description='Update replication configuration Staging Area Tags request.'
    )
    useDedicatedReplicationServer: Optional[bool] = Field(
        None,
        description='Update replication configuration use dedicated Replication Server request.',
    )


class Application(BaseModel):
    applicationAggregatedStatus: Optional[ApplicationAggregatedStatus] = None
    applicationID: Optional[ApplicationID] = None
    arn: Optional[ARN] = None
    creationDateTime: Optional[ISO8601DatetimeString] = None
    description: Optional[ApplicationDescription] = None
    isArchived: Optional[Boolean] = None
    lastModifiedDateTime: Optional[ISO8601DatetimeString] = None
    name: Optional[ApplicationName] = None
    tags: Optional[TagsMap] = None
    waveID: Optional[WaveID] = None


class ApplicationsList(RootModel[List[Application]]):
    root: List[Application]


class AssociateSourceServersRequest(BaseModel):
    applicationID: ApplicationID
    sourceServerIDs: AssociateSourceServersRequestSourceServerIDs


class ChangeServerLifeCycleStateRequest(BaseModel):
    lifeCycle: ChangeServerLifeCycleStateSourceServerLifecycle
    sourceServerID: SourceServerID


class CreateReplicationConfigurationTemplateRequest(BaseModel):
    associateDefaultSecurityGroup: Boolean
    bandwidthThrottling: PositiveInteger
    createPublicIP: Boolean
    dataPlaneRouting: ReplicationConfigurationDataPlaneRouting
    defaultLargeStagingDiskType: ReplicationConfigurationDefaultLargeStagingDiskType
    ebsEncryption: ReplicationConfigurationEbsEncryption
    ebsEncryptionKeyArn: Optional[ARN] = None
    replicationServerInstanceType: EC2InstanceType
    replicationServersSecurityGroupsIDs: ReplicationServersSecurityGroupsIDs
    stagingAreaSubnetId: SubnetID
    stagingAreaTags: TagsMap
    tags: Optional[TagsMap] = None
    useDedicatedReplicationServer: Boolean


class DataReplicationInitiation(BaseModel):
    nextAttemptDateTime: Optional[ISO8601DatetimeString] = None
    startDateTime: Optional[ISO8601DatetimeString] = None
    steps: Optional[DataReplicationInitiationSteps] = None


class DescribeJobsRequestFilters(BaseModel):
    fromDate: Optional[ISO8601DatetimeString] = None
    jobIDs: Optional[DescribeJobsRequestFiltersJobIDs] = None
    toDate: Optional[ISO8601DatetimeString] = None


class DescribeSourceServersRequestFilters(BaseModel):
    applicationIDs: Optional[DescribeSourceServersRequestApplicationIDs] = None
    isArchived: Optional[Boolean] = None
    lifeCycleStates: Optional[LifeCycleStates] = None
    replicationTypes: Optional[ReplicationTypes] = None
    sourceServerIDs: Optional[DescribeSourceServersRequestFiltersIDs] = None


class DescribeVcenterClientsResponse(BaseModel):
    items: Optional[VcenterClientList] = None
    nextToken: Optional[PaginationToken] = None


class DisassociateSourceServersRequest(BaseModel):
    applicationID: ApplicationID
    sourceServerIDs: DisassociateSourceServersRequestSourceServerIDs


class ExportErrors(RootModel[List[ExportTaskError]]):
    root: List[ExportTaskError]


class ExportTask(BaseModel):
    creationDateTime: Optional[ISO8601DatetimeString] = None
    endDateTime: Optional[ISO8601DatetimeString] = None
    exportID: Optional[ExportID] = None
    progressPercentage: Optional[Float] = None
    s3Bucket: Optional[S3BucketName] = None
    s3BucketOwner: Optional[AccountID] = None
    s3Key: Optional[S3Key] = None
    status: Optional[ExportStatus] = None
    summary: Optional[ExportTaskSummary] = None


class ExportsList(RootModel[List[ExportTask]]):
    root: List[ExportTask]


class ImportErrors(RootModel[List[ImportTaskError]]):
    root: List[ImportTaskError]


class ImportTaskSummary(BaseModel):
    applications: Optional[ImportTaskSummaryApplications] = None
    servers: Optional[ImportTaskSummaryServers] = None
    waves: Optional[ImportTaskSummaryWaves] = None


class JobLog(BaseModel):
    event: Optional[JobLogEvent] = None
    eventData: Optional[JobLogEventData] = None
    logDateTime: Optional[ISO8601DatetimeString] = None


class JobLogs(RootModel[List[JobLog]]):
    root: List[JobLog]


class LifeCycle(BaseModel):
    addedToServiceDateTime: Optional[ISO8601DatetimeString] = None
    elapsedReplicationDuration: Optional[ISO8601DurationString] = None
    firstByteDateTime: Optional[ISO8601DatetimeString] = None
    lastCutover: Optional[LifeCycleLastCutover] = None
    lastSeenByServiceDateTime: Optional[ISO8601DatetimeString] = None
    lastTest: Optional[LifeCycleLastTest] = None
    state: Optional[LifeCycleState] = None


class ListApplicationsRequest(BaseModel):
    filters: Optional[ListApplicationsRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ListApplicationsResponse(BaseModel):
    items: Optional[ApplicationsList] = None
    nextToken: Optional[PaginationToken] = None


class ListExportErrorsResponse(BaseModel):
    items: Optional[ExportErrors] = None
    nextToken: Optional[PaginationToken] = None


class ListExportsRequest(BaseModel):
    filters: Optional[ListExportsRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ListExportsResponse(BaseModel):
    items: Optional[ExportsList] = None
    nextToken: Optional[PaginationToken] = None


class ListImportErrorsResponse(BaseModel):
    items: Optional[ImportErrors] = None
    nextToken: Optional[PaginationToken] = None


class ListWavesRequest(BaseModel):
    filters: Optional[ListWavesRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ReplicationConfiguration(BaseModel):
    associateDefaultSecurityGroup: Optional[Boolean] = None
    bandwidthThrottling: Optional[PositiveInteger] = None
    createPublicIP: Optional[Boolean] = None
    dataPlaneRouting: Optional[ReplicationConfigurationDataPlaneRouting] = None
    defaultLargeStagingDiskType: Optional[
        ReplicationConfigurationDefaultLargeStagingDiskType
    ] = None
    ebsEncryption: Optional[ReplicationConfigurationEbsEncryption] = None
    ebsEncryptionKeyArn: Optional[ARN] = None
    name: Optional[SmallBoundedString] = None
    replicatedDisks: Optional[ReplicationConfigurationReplicatedDisks] = None
    replicationServerInstanceType: Optional[EC2InstanceType] = None
    replicationServersSecurityGroupsIDs: Optional[
        ReplicationServersSecurityGroupsIDs
    ] = None
    sourceServerID: Optional[SourceServerID] = None
    stagingAreaSubnetId: Optional[SubnetID] = None
    stagingAreaTags: Optional[TagsMap] = None
    useDedicatedReplicationServer: Optional[Boolean] = None


class ReplicationConfigurationTemplate(BaseModel):
    arn: Optional[ARN] = None
    associateDefaultSecurityGroup: Optional[Boolean] = None
    bandwidthThrottling: Optional[PositiveInteger] = None
    createPublicIP: Optional[Boolean] = None
    dataPlaneRouting: Optional[ReplicationConfigurationDataPlaneRouting] = None
    defaultLargeStagingDiskType: Optional[
        ReplicationConfigurationDefaultLargeStagingDiskType
    ] = None
    ebsEncryption: Optional[ReplicationConfigurationEbsEncryption] = None
    ebsEncryptionKeyArn: Optional[ARN] = None
    replicationConfigurationTemplateID: ReplicationConfigurationTemplateID
    replicationServerInstanceType: Optional[EC2InstanceType] = None
    replicationServersSecurityGroupsIDs: Optional[
        ReplicationServersSecurityGroupsIDs
    ] = None
    stagingAreaSubnetId: Optional[SubnetID] = None
    stagingAreaTags: Optional[TagsMap] = None
    tags: Optional[TagsMap] = None
    useDedicatedReplicationServer: Optional[Boolean] = None


class ReplicationConfigurationTemplates(
    RootModel[List[ReplicationConfigurationTemplate]]
):
    root: List[ReplicationConfigurationTemplate]


class SsmDocumentParameters(
    RootModel[Optional[Dict[str, SsmParameterStoreParameters]]]
):
    root: Optional[Dict[str, SsmParameterStoreParameters]] = None


class StartExportResponse(BaseModel):
    exportTask: Optional[ExportTask] = None


class TemplateActionDocument(BaseModel):
    actionID: Optional[ActionID] = None
    actionName: Optional[BoundedString] = None
    active: Optional[Boolean] = None
    category: Optional[ActionCategory] = None
    description: Optional[ActionDescription] = None
    documentIdentifier: Optional[BoundedString] = None
    documentVersion: Optional[DocumentVersion] = None
    externalParameters: Optional[SsmDocumentExternalParameters] = None
    mustSucceedForCutover: Optional[Boolean] = None
    operatingSystem: Optional[OperatingSystemString] = None
    order: Optional[OrderType] = None
    parameters: Optional[SsmDocumentParameters] = None
    timeoutSeconds: Optional[StrictlyPositiveInteger] = None


class TemplateActionDocuments(RootModel[List[TemplateActionDocument]]):
    root: List[TemplateActionDocument] = Field(..., max_length=100, min_length=0)


class Wave(BaseModel):
    arn: Optional[ARN] = None
    creationDateTime: Optional[ISO8601DatetimeString] = None
    description: Optional[WaveDescription] = None
    isArchived: Optional[Boolean] = None
    lastModifiedDateTime: Optional[ISO8601DatetimeString] = None
    name: Optional[WaveName] = None
    tags: Optional[TagsMap] = None
    waveAggregatedStatus: Optional[WaveAggregatedStatus] = None
    waveID: Optional[WaveID] = None


class WavesList(RootModel[List[Wave]]):
    root: List[Wave]


class DataReplicationInfo(BaseModel):
    dataReplicationError: Optional[DataReplicationError] = None
    dataReplicationInitiation: Optional[DataReplicationInitiation] = None
    dataReplicationState: Optional[DataReplicationState] = None
    etaDateTime: Optional[ISO8601DatetimeString] = None
    lagDuration: Optional[ISO8601DurationString] = None
    lastSnapshotDateTime: Optional[ISO8601DatetimeString] = None
    replicatedDisks: Optional[DataReplicationInfoReplicatedDisks] = None


class DescribeJobLogItemsResponse(BaseModel):
    items: Optional[JobLogs] = None
    nextToken: Optional[PaginationToken] = None


class DescribeJobsRequest(BaseModel):
    filters: Optional[DescribeJobsRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class DescribeReplicationConfigurationTemplatesResponse(BaseModel):
    items: Optional[ReplicationConfigurationTemplates] = None
    nextToken: Optional[PaginationToken] = None


class DescribeSourceServersRequest(BaseModel):
    filters: Optional[DescribeSourceServersRequestFilters] = None
    maxResults: Optional[MaxResultsType] = None
    nextToken: Optional[PaginationToken] = None


class ImportTask(BaseModel):
    creationDateTime: Optional[ISO8601DatetimeString] = None
    endDateTime: Optional[ISO8601DatetimeString] = None
    importID: Optional[ImportID] = None
    progressPercentage: Optional[Float] = None
    s3BucketSource: Optional[S3BucketSource] = None
    status: Optional[ImportStatus] = None
    summary: Optional[ImportTaskSummary] = None


class ListTemplateActionsResponse(BaseModel):
    items: Optional[TemplateActionDocuments] = None
    nextToken: Optional[PaginationToken] = None


class ListWavesResponse(BaseModel):
    items: Optional[WavesList] = None
    nextToken: Optional[PaginationToken] = None


class PutSourceServerActionRequest(BaseModel):
    actionID: ActionID
    actionName: ActionName
    active: Optional[Boolean] = None
    category: Optional[ActionCategory] = None
    description: Optional[ActionDescription] = None
    documentIdentifier: BoundedString
    documentVersion: Optional[DocumentVersion] = None
    externalParameters: Optional[SsmDocumentExternalParameters] = None
    mustSucceedForCutover: Optional[Boolean] = None
    order: OrderType
    parameters: Optional[SsmDocumentParameters] = None
    sourceServerID: SourceServerID
    timeoutSeconds: Optional[StrictlyPositiveInteger] = None


class PutTemplateActionRequest(BaseModel):
    actionID: ActionID
    actionName: BoundedString
    active: Optional[Boolean] = None
    category: Optional[ActionCategory] = None
    description: Optional[ActionDescription] = None
    documentIdentifier: BoundedString
    documentVersion: Optional[DocumentVersion] = None
    externalParameters: Optional[SsmDocumentExternalParameters] = None
    launchConfigurationTemplateID: LaunchConfigurationTemplateID
    mustSucceedForCutover: Optional[Boolean] = None
    operatingSystem: Optional[OperatingSystemString] = None
    order: OrderType
    parameters: Optional[SsmDocumentParameters] = None
    timeoutSeconds: Optional[StrictlyPositiveInteger] = None


class SourceServer(BaseModel):
    applicationID: Optional[ApplicationID] = None
    arn: Optional[ARN] = None
    dataReplicationInfo: Optional[DataReplicationInfo] = None
    fqdnForActionFramework: Optional[BoundedString] = None
    isArchived: Optional[Boolean] = None
    launchedInstance: Optional[LaunchedInstance] = None
    lifeCycle: Optional[LifeCycle] = None
    replicationType: Optional[ReplicationType] = None
    sourceProperties: Optional[SourceProperties] = None
    sourceServerID: Optional[SourceServerID] = None
    tags: Optional[TagsMap] = None
    userProvidedID: Optional[BoundedString] = None
    vcenterClientID: Optional[VcenterClientID] = None


class SourceServerActionDocument(BaseModel):
    actionID: Optional[ActionID] = None
    actionName: Optional[ActionName] = None
    active: Optional[Boolean] = None
    category: Optional[ActionCategory] = None
    description: Optional[ActionDescription] = None
    documentIdentifier: Optional[BoundedString] = None
    documentVersion: Optional[DocumentVersion] = None
    externalParameters: Optional[SsmDocumentExternalParameters] = None
    mustSucceedForCutover: Optional[Boolean] = None
    order: Optional[OrderType] = None
    parameters: Optional[SsmDocumentParameters] = None
    timeoutSeconds: Optional[StrictlyPositiveInteger] = None


class SourceServerActionDocuments(RootModel[List[SourceServerActionDocument]]):
    root: List[SourceServerActionDocument] = Field(..., max_length=100, min_length=0)


class SourceServersList(RootModel[List[SourceServer]]):
    root: List[SourceServer]


class SsmDocument(BaseModel):
    actionName: BoundedString
    externalParameters: Optional[SsmDocumentExternalParameters] = None
    mustSucceedForCutover: Optional[Boolean] = None
    parameters: Optional[SsmDocumentParameters] = None
    ssmDocumentName: SsmDocumentName
    timeoutSeconds: Optional[StrictlyPositiveInteger] = None


class SsmDocuments(RootModel[List[SsmDocument]]):
    root: List[SsmDocument] = Field(..., max_length=10, min_length=0)


class StartImportResponse(BaseModel):
    importTask: Optional[ImportTask] = None


class PostLaunchActions(BaseModel):
    cloudWatchLogGroupName: Optional[CloudWatchLogGroupName] = None
    deployment: Optional[PostLaunchActionsDeploymentType] = None
    s3LogBucket: Optional[S3LogBucketName] = None
    s3OutputKeyPrefix: Optional[BoundedString] = None
    ssmDocuments: Optional[SsmDocuments] = None


class CreateLaunchConfigurationTemplatePostRequest(BaseModel):
    associatePublicIpAddress: Optional[bool] = Field(
        None, description='Associate public Ip address.'
    )
    bootMode: Optional[BootMode] = Field(
        None, description='Launch configuration template boot mode.'
    )
    copyPrivateIp: Optional[bool] = Field(None, description='Copy private Ip.')
    copyTags: Optional[bool] = Field(None, description='Copy tags.')
    enableMapAutoTagging: Optional[bool] = Field(
        None, description='Enable map auto tagging.'
    )
    largeVolumeConf: Optional[LargeVolumeConf] = Field(
        None, description='Launch template disk configuration.'
    )
    launchDisposition: Optional[LaunchDisposition] = Field(
        None, description='Launch disposition.'
    )
    licensing: Optional[Licensing] = Field(None, description='Configure Licensing.')
    mapAutoTaggingMpeID: Optional[constr(min_length=0, max_length=256)] = Field(
        None, description='Launch configuration template map auto tagging MPE ID.'
    )
    postLaunchActions: Optional[PostLaunchActions] = Field(
        None,
        description='Post Launch Actions to executed on the Test or Cutover instance.',
    )
    smallVolumeConf: Optional[SmallVolumeConf] = Field(
        None, description='Launch template disk configuration.'
    )
    smallVolumeMaxSize: Optional[conint(ge=0)] = Field(
        None, description='Small volume maximum size.'
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='Request to associate tags during creation of a Launch Configuration Template.',
    )
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = Field(None, description='Target instance type right-sizing method.')


class UpdateLaunchConfigurationPostRequest(BaseModel):
    bootMode: Optional[BootMode] = Field(
        None, description='Update Launch configuration boot mode request.'
    )
    copyPrivateIp: Optional[bool] = Field(
        None, description='Update Launch configuration copy Private IP request.'
    )
    copyTags: Optional[bool] = Field(
        None, description='Update Launch configuration copy Tags request.'
    )
    enableMapAutoTagging: Optional[bool] = Field(
        None, description='Enable map auto tagging.'
    )
    launchDisposition: Optional[LaunchDisposition] = Field(
        None, description='Update Launch configuration launch disposition request.'
    )
    licensing: Optional[Licensing] = Field(None, description='Configure Licensing.')
    mapAutoTaggingMpeID: Optional[constr(min_length=0, max_length=256)] = Field(
        None, description='Launch configuration map auto tagging MPE ID.'
    )
    name: Optional[constr(min_length=0, max_length=128)] = Field(
        None, description='Update Launch configuration name request.'
    )
    postLaunchActions: Optional[PostLaunchActions] = Field(
        None,
        description='Post Launch Actions to executed on the Test or Cutover instance.',
    )
    sourceServerID: constr(
        pattern=r'^s-[0-9a-zA-Z]{17}$', min_length=19, max_length=19
    ) = Field(
        ..., description='Update Launch configuration by Source Server ID request.'
    )
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = Field(
        None,
        description='Update Launch configuration Target instance right sizing request.',
    )


class UpdateLaunchConfigurationTemplatePostRequest(BaseModel):
    associatePublicIpAddress: Optional[bool] = Field(
        None, description='Associate public Ip address.'
    )
    bootMode: Optional[BootMode] = Field(
        None, description='Launch configuration template boot mode.'
    )
    copyPrivateIp: Optional[bool] = Field(None, description='Copy private Ip.')
    copyTags: Optional[bool] = Field(None, description='Copy tags.')
    enableMapAutoTagging: Optional[bool] = Field(
        None, description='Enable map auto tagging.'
    )
    largeVolumeConf: Optional[LargeVolumeConf] = Field(
        None, description='Launch template disk configuration.'
    )
    launchConfigurationTemplateID: constr(
        pattern=r'^lct-[0-9a-zA-Z]{17}$', min_length=21, max_length=21
    ) = Field(..., description='Launch Configuration Template ID.')
    launchDisposition: Optional[LaunchDisposition] = Field(
        None, description='Launch disposition.'
    )
    licensing: Optional[Licensing] = Field(None, description='Configure Licensing.')
    mapAutoTaggingMpeID: Optional[constr(min_length=0, max_length=256)] = Field(
        None, description='Launch configuration template map auto tagging MPE ID.'
    )
    postLaunchActions: Optional[PostLaunchActions] = Field(
        None,
        description='Post Launch Actions to executed on the Test or Cutover instance.',
    )
    smallVolumeConf: Optional[SmallVolumeConf] = Field(
        None, description='Launch template disk configuration.'
    )
    smallVolumeMaxSize: Optional[conint(ge=0)] = Field(
        None, description='Small volume maximum size.'
    )
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = Field(None, description='Target instance type right-sizing method.')


class DescribeSourceServersResponse(BaseModel):
    items: Optional[SourceServersList] = None
    nextToken: Optional[PaginationToken] = None


class ImportList(RootModel[List[ImportTask]]):
    root: List[ImportTask]


class JobPostLaunchActionsLaunchStatus(BaseModel):
    executionID: Optional[BoundedString] = None
    executionStatus: Optional[PostLaunchActionExecutionStatus] = None
    failureReason: Optional[BoundedString] = None
    ssmDocument: Optional[SsmDocument] = None
    ssmDocumentType: Optional[SsmDocumentType] = None


class ListImportsResponse(BaseModel):
    items: Optional[ImportList] = None
    nextToken: Optional[PaginationToken] = None


class ListSourceServerActionsResponse(BaseModel):
    items: Optional[SourceServerActionDocuments] = None
    nextToken: Optional[PaginationToken] = None


class PostLaunchActionsLaunchStatusList(
    RootModel[List[JobPostLaunchActionsLaunchStatus]]
):
    root: List[JobPostLaunchActionsLaunchStatus]


class PostLaunchActionsStatus(BaseModel):
    postLaunchActionsLaunchStatusList: Optional[PostLaunchActionsLaunchStatusList] = (
        None
    )
    ssmAgentDiscoveryDatetime: Optional[ISO8601DatetimeString] = None


class UpdateLaunchConfigurationRequest(BaseModel):
    bootMode: Optional[BootMode] = None
    copyPrivateIp: Optional[Boolean] = None
    copyTags: Optional[Boolean] = None
    enableMapAutoTagging: Optional[Boolean] = None
    launchDisposition: Optional[LaunchDisposition] = None
    licensing: Optional[Licensing] = None
    mapAutoTaggingMpeID: Optional[TagValue] = None
    name: Optional[SmallBoundedString] = None
    postLaunchActions: Optional[PostLaunchActions] = None
    sourceServerID: SourceServerID
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = None


class UpdateLaunchConfigurationTemplateRequest(BaseModel):
    associatePublicIpAddress: Optional[Boolean] = None
    bootMode: Optional[BootMode] = None
    copyPrivateIp: Optional[Boolean] = None
    copyTags: Optional[Boolean] = None
    enableMapAutoTagging: Optional[Boolean] = None
    largeVolumeConf: Optional[LaunchTemplateDiskConf] = None
    launchConfigurationTemplateID: LaunchConfigurationTemplateID
    launchDisposition: Optional[LaunchDisposition] = None
    licensing: Optional[Licensing] = None
    mapAutoTaggingMpeID: Optional[TagValue] = None
    postLaunchActions: Optional[PostLaunchActions] = None
    smallVolumeConf: Optional[LaunchTemplateDiskConf] = None
    smallVolumeMaxSize: Optional[PositiveInteger] = None
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = None


class CreateLaunchConfigurationTemplateRequest(BaseModel):
    associatePublicIpAddress: Optional[Boolean] = None
    bootMode: Optional[BootMode] = None
    copyPrivateIp: Optional[Boolean] = None
    copyTags: Optional[Boolean] = None
    enableMapAutoTagging: Optional[Boolean] = None
    largeVolumeConf: Optional[LaunchTemplateDiskConf] = None
    launchDisposition: Optional[LaunchDisposition] = None
    licensing: Optional[Licensing] = None
    mapAutoTaggingMpeID: Optional[TagValue] = None
    postLaunchActions: Optional[PostLaunchActions] = None
    smallVolumeConf: Optional[LaunchTemplateDiskConf] = None
    smallVolumeMaxSize: Optional[PositiveInteger] = None
    tags: Optional[TagsMap] = None
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = None


class LaunchConfiguration(BaseModel):
    bootMode: Optional[BootMode] = None
    copyPrivateIp: Optional[Boolean] = None
    copyTags: Optional[Boolean] = None
    ec2LaunchTemplateID: Optional[BoundedString] = None
    enableMapAutoTagging: Optional[Boolean] = None
    launchDisposition: Optional[LaunchDisposition] = None
    licensing: Optional[Licensing] = None
    mapAutoTaggingMpeID: Optional[TagValue] = None
    name: Optional[SmallBoundedString] = None
    postLaunchActions: Optional[PostLaunchActions] = None
    sourceServerID: Optional[SourceServerID] = None
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = None


class LaunchConfigurationTemplate(BaseModel):
    arn: Optional[ARN] = None
    associatePublicIpAddress: Optional[Boolean] = None
    bootMode: Optional[BootMode] = None
    copyPrivateIp: Optional[Boolean] = None
    copyTags: Optional[Boolean] = None
    ec2LaunchTemplateID: Optional[EC2LaunchConfigurationTemplateID] = None
    enableMapAutoTagging: Optional[Boolean] = None
    largeVolumeConf: Optional[LaunchTemplateDiskConf] = None
    launchConfigurationTemplateID: LaunchConfigurationTemplateID
    launchDisposition: Optional[LaunchDisposition] = None
    licensing: Optional[Licensing] = None
    mapAutoTaggingMpeID: Optional[TagValue] = None
    postLaunchActions: Optional[PostLaunchActions] = None
    smallVolumeConf: Optional[LaunchTemplateDiskConf] = None
    smallVolumeMaxSize: Optional[PositiveInteger] = None
    tags: Optional[TagsMap] = None
    targetInstanceTypeRightSizingMethod: Optional[
        TargetInstanceTypeRightSizingMethod
    ] = None


class LaunchConfigurationTemplates(RootModel[List[LaunchConfigurationTemplate]]):
    root: List[LaunchConfigurationTemplate] = Field(..., max_length=200, min_length=0)


class ParticipatingServer(BaseModel):
    launchStatus: Optional[LaunchStatus] = None
    launchedEc2InstanceID: Optional[EC2InstanceID] = None
    postLaunchActionsStatus: Optional[PostLaunchActionsStatus] = None
    sourceServerID: SourceServerID


class ParticipatingServers(RootModel[List[ParticipatingServer]]):
    root: List[ParticipatingServer]


class DescribeLaunchConfigurationTemplatesResponse(BaseModel):
    items: Optional[LaunchConfigurationTemplates] = None
    nextToken: Optional[PaginationToken] = None


class Job(BaseModel):
    arn: Optional[ARN] = None
    creationDateTime: Optional[ISO8601DatetimeString] = None
    endDateTime: Optional[ISO8601DatetimeString] = None
    initiatedBy: Optional[InitiatedBy] = None
    jobID: JobID
    participatingServers: Optional[ParticipatingServers] = None
    status: Optional[JobStatus] = None
    tags: Optional[TagsMap] = None
    type: Optional[JobType] = None


class JobsList(RootModel[List[Job]]):
    root: List[Job]


class StartCutoverResponse(BaseModel):
    job: Optional[Job] = None


class StartTestResponse(BaseModel):
    job: Optional[Job] = None


class TerminateTargetInstancesResponse(BaseModel):
    job: Optional[Job] = None


class DescribeJobsResponse(BaseModel):
    items: Optional[JobsList] = None
    nextToken: Optional[PaginationToken] = None
